import React from 'react';

import Head from 'next/head';
import Link from 'next/link';

import * as Styles from './Page.styles';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Styles.TestDasha>
          Go to <Link href="/artists/first-artist">First Artist!</Link>
        </Styles.TestDasha>
      </main>
    </div>
  );
}
